/**
 * Auto-compaction service.
 *
 * When the conversation grows past a threshold of the model's context
 * window, we summarize old turns and replace them with a compact summary
 * message. Recent turns are preserved verbatim so the agent has full
 * fidelity on its most-relevant context.
 *
 * Strategy:
 *
 *   1. Always preserve the system message and the most recent N turns
 *      (default: last 6 turns ≈ 12 messages with tool calls).
 *   2. Summarize everything older into a single "context summary" message
 *      inserted right after the system message.
 *   3. The summary is generated by calling the model itself with a
 *      compaction prompt — keep facts (decisions, file paths edited,
 *      project state) and drop ceremony (greeting, narration).
 *
 * Triggers:
 *
 *   - Automatic: when estimated tokens > `auto_threshold * ctxWindow`
 *     (default 0.70). Triggered between turns, not mid-turn.
 *   - Manual: /compact slash command.
 *
 * The summary message is marked with a sentinel content prefix
 * `[CTX_SUMMARY]` so the agent knows what it is and we can recognise/skip
 * it on re-compaction.
 */

import type { Message } from '../llm/types.js';
import { logger } from './logger.js';
import { countTokens, countTokensJson } from './tokenizer.js';

const SUMMARY_PREFIX = '[CTX_SUMMARY]';

export interface CompactionResult {
  /** New, shorter message list */
  messages: Message[];
  /** Estimated tokens before compaction */
  before: number;
  /** Estimated tokens after compaction */
  after: number;
  /** Turns folded into the summary */
  turnsCompacted: number;
}

const COMPACTION_PROMPT = `You are compressing the early part of a coding-agent conversation. Your output will REPLACE the original messages, so it must capture every fact the agent might need later, in the smallest possible space.

Produce a single short summary covering:

1. **User's goal(s)** — what they're ultimately trying to accomplish, in their words.
2. **Exact paths the user named** — any absolute or relative file/directory path the USER explicitly gave (e.g. "the frontend is at cctv_frontend/src/", "edit src/pages/HomePage.jsx"). Quote them VERBATIM. These are the most important facts to preserve — losing them sends the agent searching in the wrong place. Include which directory is the frontend vs backend if that was established.
3. **Decisions made** — choices the agent committed to (tech stack picks, design choices, file structure). Critical: if the agent decided "we're using Zustand for state", that decision must survive compaction.
4. **Files touched and what changed** — each file path + 1-line description of the edit. Bullet list.
5. **Open todos / blockers** — anything mentioned but not yet completed.
6. **Project facts learned** — discoveries about the codebase the agent will need (e.g. "tests run with vitest", "DB schema has a users.email field", "API base is http://localhost:8000/api").
7. **Standing constraints** — explicit user instructions that remain in force (e.g. "do NOT run npm install or start servers", "show code before applying"). These MUST survive.

Drop:
- Greetings, pleasantries, acknowledgments
- The agent's intermediate narrations ("let me look at..." / "now I'll...")
- Long tool outputs (replace with "[examined X]" if relevant)
- Code blocks longer than 3 lines (replace with a 1-line description)

Output format: plain markdown, 200-500 tokens TOTAL. Start with "${SUMMARY_PREFIX}".
DO NOT explain what you're doing — just produce the summary.`;

export function estimateTokens(messages: Message[]): number {
  let total = 0;
  for (const m of messages) {
    const content: any = m.content;
    if (typeof content === 'string') total += countTokens(content);
    else if (Array.isArray(content)) {
      for (const part of content) {
        if (typeof part === 'object' && part && 'text' in part && typeof part.text === 'string') {
          total += countTokens(part.text);
        }
      }
    }
    if ('tool_calls' in m && Array.isArray((m as any).tool_calls)) {
      for (const tc of (m as any).tool_calls) {
        total += countTokensJson(tc);
      }
    }
    // Per-message overhead (role tags, delimiters) — ~4 tokens each in chat formats.
    total += 4;
  }
  return total;
}

export function isSummaryMessage(m: Message): boolean {
  return m.role === 'system' && typeof m.content === 'string' && m.content.includes(SUMMARY_PREFIX);
}

/**
 * Build a list of messages to send to the model for summarization.
 * The full older portion of the conversation goes in as a "user" message
 * so the model produces a single text summary.
 */
function buildCompactionRequest(toSummarize: Message[]): Message[] {
  // Render the messages into a single readable transcript
  const lines: string[] = [];
  for (const m of toSummarize) {
    const role = m.role.toUpperCase();
    if (typeof m.content === 'string' && m.content.trim()) {
      lines.push(`### ${role}\n${m.content}`);
    }
    if ('tool_calls' in m && Array.isArray((m as any).tool_calls)) {
      for (const tc of (m as any).tool_calls) {
        const fn = tc.function?.name ?? 'tool';
        const argsStr = typeof tc.function?.arguments === 'string'
          ? tc.function.arguments
          : JSON.stringify(tc.function?.arguments ?? {});
        lines.push(`### ${role} → tool call: ${fn}\n${argsStr.slice(0, 500)}`);
      }
    }
    if (m.role === 'tool' && typeof m.content === 'string') {
      lines.push(`### TOOL RESULT (${(m as any).name ?? '?'})\n${m.content.slice(0, 2000)}`);
    }
  }
  return [
    { role: 'system', content: COMPACTION_PROMPT },
    { role: 'user', content: lines.join('\n\n') },
  ];
}

/**
 * Compact a message list by summarizing all but the most recent `keepLast` turns.
 * A "turn" is a user message + everything until the next user message.
 *
 * The caller provides a `summarize` callback that runs an LLM call on the
 * messages-to-summarize and returns the summary text.
 */
export async function compactMessages(
  messages: Message[],
  options: {
    keepLastTurns?: number;
    summarize: (msgs: Message[]) => Promise<string>;
  },
): Promise<CompactionResult> {
  const keepLastTurns = options.keepLastTurns ?? 6;
  const before = estimateTokens(messages);

  const system = messages.filter(m => m.role === 'system');
  const nonSystem = messages.filter(m => m.role !== 'system');

  // Group into turn-groups: user msg starts each group
  const groups: Message[][] = [];
  let cur: Message[] = [];
  for (const m of nonSystem) {
    if (m.role === 'user' && cur.length > 0) {
      groups.push(cur);
      cur = [m];
    } else {
      cur.push(m);
    }
  }
  if (cur.length > 0) groups.push(cur);

  if (groups.length <= keepLastTurns) {
    // Nothing to do
    return { messages, before, after: before, turnsCompacted: 0 };
  }

  const toSummarize = groups.slice(0, groups.length - keepLastTurns).flat();
  const toKeep = groups.slice(groups.length - keepLastTurns).flat();
  const turnsCompacted = groups.length - keepLastTurns;

  // Filter out existing summary messages from the to-summarize set
  // and keep ALL system messages (including any prior summary) so the new
  // summary CAN reference them.
  const summarizationInput = buildCompactionRequest(toSummarize);
  let summaryText: string;
  try {
    summaryText = await options.summarize(summarizationInput);
  } catch (e: any) {
    logger.warn('Compaction summarization failed; returning original messages', { err: e?.message });
    return { messages, before, after: before, turnsCompacted: 0 };
  }
  if (!summaryText.includes(SUMMARY_PREFIX)) {
    summaryText = `${SUMMARY_PREFIX}\n${summaryText}`;
  }
  const summaryMsg: Message = { role: 'system', content: summaryText };

  const out = [
    ...system, // original system prompt
    summaryMsg, // injected summary
    ...toKeep,
  ];
  const after = estimateTokens(out);
  logger.info('Compaction complete', { turnsCompacted, before, after, savedTokens: before - after });
  return { messages: out, before, after, turnsCompacted };
}

/**
 * Check whether compaction should fire based on a threshold.
 */
export function shouldCompact(messages: Message[], ctxWindow: number, threshold = 0.70): boolean {
  const tokens = estimateTokens(messages);
  return tokens > Math.floor(ctxWindow * threshold);
}
